name: "fasttrack_cost_reporting"
version: "2.0.0"

require-dbt-version: [">=1.8.0", "<2.0.0"]

profile: "fasttrack_cost_reporting" # must exist within $HOME/.dbt/profiles.yml

macro-paths: ["macros"]
model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["dbt_packages", "logs", "target"]

dispatch:
  - macro_namespace: "dbt"
    search_order: 
      - "fasttrack_cost_reporting"
      - "dbt_snowflake_monitoring"
      - "dbt"

query-comment:
  comment: "{{ dbt_snowflake_monitoring.get_query_comment(node) }}"
  append: true

tests:
  +docs: { node_color: "#696969" }

models:
  +persist_docs: { columns: true, relation: true }

  dbt_snowflake_monitoring:
    +schema: "landing_snowflake_monitoring" # can be changed by users via src. overrides
    +docs: { node_color: "#1E90FF" }

  fasttrack_cost_reporting:
    +materialized: "view"

    staging:
      +schema: "transform_cost_reporting" # can be changed by users via src. overrides
      +docs: { node_color: "#663399" }

    transform:
      +schema: "transform_cost_reporting" # can be changed by users via src. overrides
      +docs: { node_color: "#FF4500" }

      final:
        +materialized: "table"

    publish:
      +schema: "publish_cost_reporting" # can be changed by users via src. overrides
      +docs: { node_color: "#DC143C" }

vars:
  dbt_constraints:
    # enable/disable pushing model constraints to the target db  
    dbt_constraints_enabled: true

  dbt_snowflake_monitoring:
    # optional dbt cloud metadata, used to enrich dbt-tagged snowflake monitoring data
    dbt_cloud_account_id: 5235
    dbt_cloud_run_url: "https://cloud.getdbt.com/deploy/"

  fasttrack_cost_reporting:
    # azure tags key/value for fasttrack (costs in other tags will not be taken into account)
    fasttrack_cost_reporting:azure_tags_key: "ProjectName"
    fasttrack_cost_reporting:azure_tags_value: "Fast Track Development"
