name: "fasttrack_cost_reporting"
version: "1.1.0"

require-dbt-version: [">=1.8.0", "<2.0.0"]

profile: "fasttrack_cost_reporting" # must exist within $HOME/.dbt/profiles.yml

macro-paths: ["macros"]
model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["dbt_packages", "logs", "target"]

dispatch:
  - macro_namespace: "dbt"
    search_order: 
      - "fasttrack_cost_reporting"
      - "dbt_snowflake_monitoring"
      - "dbt"

query-comment:
  comment: "{{ dbt_snowflake_monitoring.get_query_comment(node) }}"
  append: true

#### \/ uncomment to bypass snowflake extras
# sources:
#   dbt_snowflake_monitoring:
#     staging:
#       snowflake_account_usage:
#         access_history: { +enabled: false }
#         query_history: { +enabled: false }
#         warehouse_events_history: { +enabled: false }
#         warehouse_metering_history: { +enabled: false }
#### /\ uncomment to bypass snowflake extras

tests:
  +docs: { node_color: "#696969" }

models:
  +persist_docs: { columns: true, relation: true }

  dbt_snowflake_monitoring:
    +schema: "landing_snowflake_monitoring" # can be changed by users via src. overrides
    +docs: { node_color: "#1E90FF" }

    #### \/ uncomment to bypass snowflake extras
    # cost_per_query: { +enabled: false }
    # dbt_queries: { +enabled: false }
    # query_base_object_access: { +enabled: false }
    # query_base_table_access: { +enabled: false }
    # query_direct_object_access: { +enabled: false }
    # query_direct_table_access: { +enabled: false }
    # query_history_enriched: { +enabled: false }
    # warehouse_credits_map: { +enabled: false }
    # warehouses_type2_dimension: { +enabled: false }

    # staging:
    #   stg_access_history: { +enabled: false }
    #   stg_query_history: { +enabled: false }
    #   stg_warehouse_metering_history: { +enabled: false }
    #### /\ uncomment to bypass snowflake extras

  fasttrack_cost_reporting:
    +materialized: "view"

    staging:
      +schema: "transform_cost_reporting" # can be changed by users via src. overrides
      +docs: { node_color: "#663399" }

    transform:
      +schema: "transform_cost_reporting" # can be changed by users via src. overrides
      +docs: { node_color: "#FF4500" }

      final:
        +materialized: "table"

    publish:
      +schema: "publish_cost_reporting" # can be changed by users via src. overrides
      +docs: { node_color: "#DC143C" }
      +post-hook: "{{ grant_read_on_schema_objects() }}" # could also be managed via future grants

vars:
  dbt_cloud_account_id: 5235 # used on sf extras
  dbt_cloud_run_url: "https://cloud.getdbt.com/deploy/" # used on sf extras, depends on cloud region
  dbt_constraints_enabled: true
  fasttrack_cost_reporting_azure_tags_key: "ProjectName"
  fasttrack_cost_reporting_azure_tags_value: "Fast Track Development"
  fasttrack_cost_reporting_read_roles: "reporter_ft" # comma-separated role prefixes ('' to disable)
