config:
  debug: true # <true | false>
  # fail_fast: <true | false>
  # log_format: <text | json | default>
  # partial_parse: <true | false>
  # printer_width: <integer>
  send_anonymous_usage_stats: false # <true | false>
  # static_parser: <true | false>
  # use_colors: <true | false>
  # use_experimental_parser: <true | false>
  # version_check: <true | false>
  # warn_error_options: <include: all | include: [<error-name>] | include: all, exclude: [<error-name>]>
  # warn_error: <true | false>
  # write_json: <true | false>

default:
  target: dev
  outputs:
    dev:
      type: snowflake

      client_session_keep_alive: false
      threads: 8

      account: "{{ env_var('SNOWSQL_ACCOUNT') }}"
      database: "{{ env_var('SNOWSQL_DATABASE') }}"
      password: "{{ env_var('SNOWSQL_PASSWORD') }}"
      role: "{{ env_var('SNOWSQL_ROLE') }}"
      schema: "{{ env_var('SNOWSQL_SCHEMA') }}"
      user: "{{ env_var('SNOWSQL_USER') }}"
      warehouse: "{{ env_var('SNOWSQL_WAREHOUSE') }}"
