name: "fasttrack_cost_reporting_tests"
version: "1.0.0"

profile: "fasttrack_cost_reporting_test" # must exist within $HOME/.dbt/profiles.yml

macro-paths: ["macros"]
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["dbt_packages", "logs", "target"]

dispatch:
  - macro_namespace: "dbt"
    search_order: 
      - "fasttrack_cost_reporting_tests"
      - "fasttrack_cost_reporting"
      - "dbt_snowflake_monitoring"
      - "dbt"

query-comment:
  comment: "{{ dbt_snowflake_monitoring.get_query_comment(node) }}"
  append: true

models:
  dbt_snowflake_monitoring:
    +schema: "landing_snowflake_monitoring"

  fasttrack_cost_reporting:
    staging:
      +schema: "transform_cost_reporting" # schema for stg_% models

    transform:
      +schema: "transform_cost_reporting" # schema for t_% models

    publish:
      +schema: "publish_cost_reporting" # schema for d_%, f_% models
      +post-hook:
        - "grant usage on schema {{ this.database }}.{{ this.schema }} to role reporter_ft_{{ target.name if 'def' not in target.name|lower else 'dev' }}"
        - "grant select on {{ this }} to role reporter_ft_{{ target.name if 'def' not in target.name|lower else 'dev' }}"

vars:
  dbt_constraints:
    # enable/disable pushing model constraints to the target db
    dbt_constraints_enabled: false

  dbt_snowflake_monitoring:
    # optional dbt cloud metadata, used to enrich dbt-tagged snowflake monitoring data
    dbt_cloud_account_id: 5235
    dbt_cloud_run_url: "https://cloud.getdbt.com/deploy/"

  fasttrack_cost_reporting:
    # azure tags key/value for fasttrack (costs in other tags will not be taken into account)
    fasttrack_cost_reporting:azure_tags_key: "ProjectName"
    fasttrack_cost_reporting:azure_tags_value: "Fast Track Development"
